---
# Config storage for SABnzbd
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# Shared NFS PVC for media-stack (shared by all apps)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sabnzbd-pv
  namespace: media-stack
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 8Ti
