---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-config
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: prowlarr-config
    creationPolicy: Owner
  data:
    - secretKey: db_user
      remoteRef:
        key: postgres-prowlarr-username
    - secretKey: db_password
      remoteRef:
        key: postgres-prowlarr-password
    - secretKey: api_key
      remoteRef:
        key: prowlarr-api-key
    - secretKey: username
      remoteRef:
        key: prowlarr-username
    - secretKey: password
      remoteRef:
        key: prowlarr-password
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: sabnzbd-api-key
    - secretKey: nzbgeek_api_key
      remoteRef:
        key: nzbgeek-api-key
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr-api-key
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr-api-key
