---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-media
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-prowlarr
  resources:
    requests:
      storage: 8Ti
