apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Media stack - Plex, Radarr, Sonarr, Prowlarr, etc.
# Includes all media management and download applications

resources:
  - ../../../apps/media-stack/application.yaml

labels:
  - pairs:
      app-category: media
      app-stack: media
      requires: postgres
