---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinchflat
  namespace: media-stack
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: media-stack-https-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: pinchflat.torsteinbo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pinchflat
                port:
                  number: 8945
