---
apiVersion: v1
kind: Service
metadata:
  name: pinchflat
  namespace: media-stack
spec:
  selector:
    app: pinchflat
  ports:
    - protocol: TCP
      port: 8945
      targetPort: 8945
  type: ClusterIP
