apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# BentoPDF application

resources:
  - ../../../apps/bentopdf/application.yaml

labels:
  - pairs:
      app-category: utility
      app: bentopdf
