---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-config
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: prowlarr-config
    creationPolicy: Owner
  data:
    - secretKey: db_user
      remoteRef:
        key: postgres-prowlarr-username
    - secretKey: db_password
      remoteRef:
        key: postgres-prowlarr-password
    - secretKey: api_key
      remoteRef:
        key: prowlarr-api-key
