---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-stack-pv
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 172.16.16.91
    path: /volume/a5598d8d-6b2a-4d83-8b9a-b53d7fbd2d94/.srv/.unifi-drive/plex/.data
