---
# Shared NFS PVC for media-stack (shared by all apps)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stack-media
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 8Ti
