---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-key
  namespace: homepage
spec:
  encryptedData:
    key: AgBVW/ESlYdtZjWLR9bEVKhW9WXxa8qNeASvEqgNifyjSWxmJa+JQR/YbbRksOMaE2/T3kA4tYjZhEKG4UtfqLGe/F6DzduQ5Tywugrh/uEXdIlzfBNouB6V5FIPEeWQx9hKtKdRTAFjLBBYMN5Ac1SXGclnP3B06r0N7u5I6UiN4TVS/ONOjEeK3BKaEpAYkl2pKII0BK5xl48LekKdgbY4VXw8wL7xdDTrkDgjkJwLeRt+781V7u2B4YqKTZXhRq5QoFpiPTxEo5VkLjRVuSYixute+xvT+0Q/0V/zpcBCEBe9RHgtEIP8PQmdDHkYHIwnLhV5B6z9Z8M3C5tq1akxRG0sBqnKF0aUHBhp6Wa6XLRmRbEnSjS61nMmekvH8wWIfxL8HlwmW/wYtveKyCkZEEWldvmm94j4Rxa0dRBuB9LIPMgkkqdLUzBMKOIvs3jE2S58i03hcC6FrYUPGITyfuuj/P2RLes8UgazKitU5yuaoQgR3HvbqMD83Ymhwcjky+LoU9JkaCvHKqQHdhUFY0+u5Y3DYHgMyrG5B6HA9FCcVd53jAN9tyrcdwuZvEQlR6I6mcfICZ2hJSX3r6xvbHDYmYLnbGHlk1PDsevIX9WesYqGhZZGwQUvo5k6RvVtWXoOBKHVfErr5A6ZHKA7M2ygD5b9GsSAgQ6Ro16xu7iV3ZPGYNlv8xgiHWUYvuNUfugUa5ywerXvOGP+FVPJfPXP/DGs1y2QOL2WKpK44zC8Qo/AkHwk3L317W7CaFvFimAv8BRYteaxxVXMxTPg7hZR1VBLHBtBA9mFZa71JVgKLR5VX4RxNRlSNar1rDFk0amo50GO/Uv00RUUYJnSFNPzvFU/J/BBGTBcUfJAfMwqX/OmHGcG1/gMH+/RhyBmMqCkghJD3xsMNR+pPYFHD3cW5ib+hKaWQpxI7W8VHpgvt8hWpV8efKFbclnRdtWha7VoJNfvRxvxP/lG9ZLowu4apB7ttdCTx5Sss/hVUHqdQ96Tahav7pIpGeo39lY=
    username: AgBWAU5JiN7647Tfc20vaDwxQT0LmNcvML0JI1scwPw2DlQvkBp9fJy0deBadtwAieSIHgvDe2uTbBlhXE3R+Og9uNjSxdUQ6/n9IBa0buiWYjeC1HHL4vH7Joe+p2bwSqQU8RbQ3oUEl2LdSYR+/7MBnaqqPzVDBOee7eB0o4AtlYl7ucjhPBIJ6T+8fGli7LhADF3Fvb5M9PmTylftSGgPIFDANRjiBSyA/m4OjCNfj90rTl3AOMx7lxUe7UANeJTsjzxf9R5AWVK2ROhD56Ng3fUWsz8tXBkUpYlESGNASwSTQ12DY9s3Lta4xRCK9D1un3xCDNOeFBLkicCJBDBf/0j4p/ZmwrthTWTSmSmO4dssDUAgs7oJRl6zxyF3o4YJN7NGcdTSRSd8cQqjEO/hDGnzbx6QPzs0ab8O2zxhS7AcXtCwtuNytpoedcK2TH+eZwVjJLfnv+0AZQ2T5mR6FheKmm4IhuXEQYBr7LmaEO5i2Ox9Py4w2/Xsvmy3KjUsFFfXEpronsI1NPsdc7VP5x181kcamo8EFWNFrKNTANjGP0tdiE4+xYQMBlmoKRboz/tGQJH3zUcMyfB2MiYCBBl/q1eGxSRUNB2a/mjgCxtfMzrng9bQs02JQHpfaXaat+0yTfZzT9G6xRy0dp0EJ+xsgbB6kmtyGVwXiqgZrSUK6twDxogIlFORs3WlZDWY/eQabHjwEw==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: argocd-key
      namespace: homepage
    type: kubernetes.io/basic-auth
