---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-key
  namespace: homepage
spec:
  encryptedData:
    key: AgCOdTv4QaodcURlYLFNMS580wO0MkJqc2gi+4fUMc/bAScXEvZ2Xs4RX3Hn1vQdxvFAmhRQttTY7TTvNGRpYUnegRFtDUPqnEohxw1/kTTeUeLCZ5fPt1ZIL48m0d+y27DPbs8utZsuO5eT9EMXH6ZIeGjJVq8rYfaXs8Gn363IvMn4t0h4BA4mB4tY0yeH6RmFT9CUIjPq1bY5PIaTXTm5z3UXX6n8E9iGx6rUEo6CyMhnDx0Efz7S9ddY5vtse7cyTVPwVlPxb7YjHzk4zzZ7FwhwrKmuVvyjB1WwaaSJ3nsMSdvlryJMdzvtc0I/y95wlCgoGzz5UYYNuqsYanJ0IhTL9fDQYui9BCQjF6YEAPEzyzFfZbIAMRn+8W7uu4WkLIZXHVp4UdlYA1wxhs2kE0JLG5DHguXmSNwoVxVVLOBUEnZr9gGjo6hOZPu/F3Ws9fXVCz/2XNOLr4AH/F3/PKQJ3sKI7ot8Iau9dAmumyPJmbNy4qn9y6XkTi4ZYUGQYbA72d7eLao0C6gytD4iR3B/TyRpReKlj6JYvfguryHSAndygvc1jvBwJcB8ufyEDTrdpDlfdDtH/lkxxaci0HhMsCUrtkhd1E7c6wG5HfifOaNbpkJhEtEScxP5LsOrd3uuHU1i9hEh7sMUR6HjQKmmLXLnWDfKXRUS/9FhalufNYYqtEU9utBIEs5CgMhtvUdl2A9klhOzrQmaJofVS6i0XYoWkOEQw/S1rMHwcMG3DWbkndeVTq6OnxnN4q9Atek/HS7AssHjGs1fs7yefRkQjuu5II1Jozkp9gHKSb/P19cmwFPK5YmbedI/9MYdEGbXjrzrZB65JUZtSLw8JBFwo+/0MgRN0MmAvUdz/7N9zeXE04b7z9QILwwYdGCyfWoG56pgwD9U5mBQr1WdrqbyG00xaD7Mkb/V7vSeSEzw+eLW+j8hKtqFBZadC+4KrTH7dpLn2vw6bJe65bsqZorBKvRTevVSaMPTNcaVPbY8tlU+lBg0pS/LqJwE3Ig=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: argocd-key
      namespace: homepage
    type: kubernetes.io/basic-auth
