apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    showNamespaces: true
  settings.yaml: |
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Media:
        - Immich:
            href: https://immich.storsteinbo.no
            description: Photo management tool
            namespace: immich
            podSelector: app=immich-server
            icon: immich.png
        - Bambustudio:
            href: https://bambustudio.torsteinbo.net
            description: Bambustudio
            namespace: bambustudio
            podSelector: app=bambustudio
            icon: bambustudio.png
        - Longhorn:
            href: https://longhorn.torsteinbo.net
            description: Longhorn
            namespace: longhorn-system
            podSelector: app=longhorn-manager
            icon: longhorn.png
            widget:
              type: longhorn
              url: http://longhorn-frontend.longhorn-system
              expanded: true
              total: true
              labels: true
              nodes: true
        - Filebrowser:
            href: https://filebrowser.torsteinbo.net
            description: Filebrowser
            namespace: filebrowser
            podSelector: app=filebrowser
            icon: filebrowser.png
            widget: 
              type: filebrowser
              url: http://filebrowser.filebrowser
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
  docker.yaml: ""