---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filebrowser-secret
  namespace: homepage
spec:
  encryptedData:
    password: AgCIbr2Rd+7xYG/tWFGkNo7i8Burq23+G+5qD5Xsw/sIbk2uXELIjI7Tlz9oL7w9PKHwUH+aOlZdFHXJhLYNoRPRNwVBtDR/V3KbfBIa8lYvBwIor+NUqDaIZz8BaynssQ//abugHljKYe/pfoR5/b+3xbSEXuCVENbzXT3rlakYlhC3NZ14j9ptO4IUfuQO7Dcr5XhmXxCy0QXh7Bi7rzt9NBbqj8n2yr9BR7bTE63Qdo4YS8KT4mSA83tmTLuCjFhOlCEkt+ai7eqziF452/d8unRYV3Ze5pagwqR15/e1x1qhV3DT72CGxSvasFKawLgcRNqPprGBxuvHndUkOjU9H28vOjBBglUmqnAUpGKc5RZyUXxy9I0xsER9O4fUW9PwekRDBal4qoZp9JF8JrVF8ZZE6LGrSxTvzRtSeRshclNXIYpzViJr10WPXGrgkxTnnx5wjYhwiD1DSzeg80LwNtFySvTAanQVhiKuEKgBCQ390UGBZVy2kGGvF4KqADh//6LP2yqNjSOK883Hd5GMXp/bAg60JfUQYvJr7WVauYgsI60uYAZBoEE6pZSPIYXAvME4wgIZyqlBQwM8S8lJV5XZh+M3MpmHVKYVmeLrifO7uOIcPHNTYwOxCyeoQ6qdCeWX1vW20IAaYUzyk6oOFpDAARr+RYS0EQb/HefGYwIG9zFYZFMsApd69LqEZP2gs28ZKZb72KUby8rMByqD
    username: AgArsZ0NSunNl5tiMat/XSPm6mYtf0PBrGa9S+oRzaWQuKTLoGrWJExaG9veW5vdP/axgLQsZe6aj7vNXmxcqU/HKdcq1Q0pGjS+LhJl0HRwgNOeM2yl7H+hy63MdBlimOADzoCo6Lo6LzL/7nl4bilbNkwf+cUjdYp0sRLnznW7HEjVmpLyWlmRQ555sI1VBfkjqd+KpdKAqbuBXtIAQ3Te+Srf+vCXj1K6TZR8nhNhij5pD06JGcDG+KGruupIb7QbzAyV+cfKr0ilKzK2plhhWw04ApZzxXAH8hatZlEGUgi5QCpGTJ5x+DFGatzoq4NYV6iGFiEuPvNInmdJMXQFr+3eiEiR65hu7pVqidLKhjAZRcoN2cFSGSx8K4vArQ9vuHAjzRC87Vz8wBLStaFjhXcwmDhWXmiCjbdNRK6sMmYSaOSf9j1NYAYR1dn+y/mglOvmldLYA2Tdd6y0eS8BWkYT1RIOch7WvUR5VK7KFdZt9t3mLXzo2Rap7JPc0Ccuxt37ICgc+J8SWi7ztAd0HJ5k4mgE3jjF6KTPBNCzJI+rvQJv9Ts8GmLvPqP2hDsDHcmTnE3RozSUsdELdo6t/7OPT4RZMroX1C8rE014JQsQdqvsmlwmZbmxHVhSl/WKjYxL3XMBGd9hTYRm8F3NXS0/RuFaxc/q83+Xt0BCLZHLAJh6MO0Wa9qpiYj59MAJCSRGmg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: filebrowser-secret
      namespace: homepage
    type: kubernetes.io/basic-auth
