---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    FILEBROWSER_PASSWORD: AgAsLC3rnSwj8iA5p+DDtuIqW1mtfA+L4PHb3y8FlaGNRhYA1v43C85Af00eY71zavomjyGaQCeuRjyEHzKU+b/MfqBWBAjZt5hLLRTZW8gpa0HvNVx1cyVdHCtwGGDvq2vdVyg75Ff8wjvj2sGO3EeTg97yx//1yp0JY2q6m10y42goxXwfCFjErHINjOTB3KX4zBbOyOLh9s7HntpvbL2jgoiw7bOWOSfIQOi6O9jN7hEQWvAFGTyjx+r4PnlckFziWt+GrsKUNm/xqFmY+67UBvOx6BQkUvAmdkyB7UfRB2ds/twBhvWVrH/q5mHTYlextO34ObLjhuxNGhns45sOa7MHyrYo2ajgaI7GzIVuVB969zGb2diXJcuQNPNZ0W1Va4/c7lMOLdmJ8e+83wR8UOBfldNNluTHHJBx4xfk4AKpKtUk4wFQknACRdWG+7FEymq6KZXKjIcejB1By0N5Z2xw4mpyY3eZSBNT4mhlP65wAgmIJmTJJsbE90WnICWls5D0zl6pZnMw7IA9AOWkPOV6rg69KWhy2ESTaK8Ev12wuDvqIJ2P14Fe8+39AAmjJEpEybUnZkbWW3AcoqwXhARmv5dJI3GCGoIPQKzJ0btorYi03EdEjG3D+/Ne5Au/7tqyleaacM+lEt6sJXe+rri2fvdPQ7+u/5q+MMOfVvMiFavmwbt8CvSSFmqN5dEKoUl0/1ncmrzEUO4c1u6H
    FILEBROWSER_USERNAME: AgAYMvMr2ds2s0JXPUWTHICcMauBqQgAZESCIqvSXiwKoex3zs75TCwKe4HXwcBWT0LxwX95Q8wCe+FFU0Q7LlPDJMEvjLGEpu6dRV1Jri8/5kLNTJWVyk4KFhDyr0T1JqfyQJUkLqYSSaK0LzcVavM3AkZkHPrqxM1nosT+vWiL5PY6n0+N9oxtDCPQELC7I9xuK21gqa0lKd+BsEznqpkeKw+j/QdgByfaCkKkd38RxiMHGctgpupR2dYhx9rQeeANQo/wnQyqiZEWEGryHYWZw9JQEw6hUpg4U4lkutLUnz76oblWHZlbXT2zOTSe8qiaIEfTbJPhDkeKSyM+Xdq4QJiGg8/Ke4ltvfm2JQbOjaBNA/se8mCXkxtSmjs45nv9z+RaPKa1LZ+uS8DqsJeIzAx3GFP+vRlduLvIoIFvCfcpcNCCKfRH6Tz/ZTxEEz3ocsqoZ386ft56vwWZiDy7ETdydc40aT9RgxrTC7m6IL5toKubn6xFbUOe9tMTrq0Oi9uyG3X23o7sseTM2jJs4j+te9p5G0p0SIzGLVj46ez6XkdaZGBYB+mJ0l/gm5yyyns0ungDLrFYRdMRzgdJYke30XIr6L4YuCvtmMA27OxJ67bE/uDNJtC8kc+5cZmin5tOW/NyvE9sbjl1r2kBJvkfTdpdltOGiSbJDUiwKNTPVGeakEkB3JyQw38syA+Eo2z19A==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: homepage-secrets
      namespace: homepage
    type: kubernetes.io/basic-auth
