apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# OpenHands AI agent platform

resources:
  - ../../../apps/openhands/application.yaml

labels:
  - pairs:
      app-category: ai
      app: openhands
