---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backup-to-cifs
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "backup"
  groups:
    - postgresql
  retain: 7
  concurrency: 2
