---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-config
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: radarr-config
    creationPolicy: Owner
  data:
    - secretKey: db_user
      remoteRef:
        key: postgres-radarr-username
    - secretKey: db_password
      remoteRef:
        key: postgres-radarr-password
    - secretKey: api_key
      remoteRef:
        key: radarr-api-key
    - secretKey: username
      remoteRef:
        key: radarr-username
    - secretKey: password
      remoteRef:
        key: radarr-password
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: sabnzbd-api-key
