apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint
  namespace: 3dprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: octoprint   # match the pod label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: octoprint
        app.kubernetes.io/component: octoprint
        app.kubernetes.io/part-of: octoprint
    spec:
      containers:
        - name: octoprint
          image: octoprint/octoprint:3.1.0
          env:
            - name: ENABLE_MJPG_STREAMER
              value: "true"
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - name: octoprint
              mountPath: /octoprint
      volumes:
        - name: octoprint
          persistentVolumeClaim:
            claimName: octoprint