apiVersion: v1
kind: Service
metadata:
  name: octoprint
  namespace: 3dprint
spec:
  selector:
    app.kubernetes.io/name: octoprint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP