---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediamanager
  namespace: mediamanager
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: mediamanager-https-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: mediamanager.torsteinbo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mediamanager
                port:
                  number: 8000
