---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buildarr-secrets
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: buildarr-secrets
    creationPolicy: Owner
  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: prowlarr-api-key
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr-api-key
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr-api-key
    - secretKey: SABNZBD_API_KEY
      remoteRef:
        key: sabnzbd-api-key
    - secretKey: NZBGEEK_API_KEY
      remoteRef:
        key: nzbgeek-api-key
    - secretKey: USENET_SERVER_HOST
      remoteRef:
        key: usenet-server-host
    - secretKey: USENET_SERVER_PORT
      remoteRef:
        key: usenet-server-port
    - secretKey: USENET_SERVER_USERNAME
      remoteRef:
        key: usenet-server-username
    - secretKey: USENET_SERVER_PASSWORD
      remoteRef:
        key: usenet-server-password
