apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# PostgreSQL database cluster and provisioned databases

resources:
  - ../../bootstrap/postgresql.yaml

labels:
  - pairs:
      component: database
      tier: postgres
