---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sonarr-media-pv
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sonarr
  nfs:
    server: 172.16.16.91
    path: /volume/a5598d8d-6b2a-4d83-8b9a-b53d7fbd2d94/.srv/.unifi-drive/plex/.data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sonarr
  resources:
    requests:
      storage: 8Ti
