apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# BambuStudio 3D printing application

resources:
  - ../../../apps/bambustudio.yaml

labels:
  - pairs:
      app-category: utility
      app: bambustudio
