apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Homepage dashboard application

resources:
  - ../../../apps/homepage.yaml

labels:
  - pairs:
      app-category: dashboard
      app: homepage
