---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr-secrets
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: configarr-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yml: |
          SONARR_API_KEY: "{{ .sonarr_api_key }}"
          RADARR_API_KEY: "{{ .radarr_api_key }}"
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: sonarr-api-key
    - secretKey: radarr_api_key
      remoteRef:
        key: radarr-api-key
