apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Karakeep application

resources:
  - ../../../apps/karakeep.yaml

labels:
  - pairs:
      app-category: productivity
      app: karakeep
