---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
spec:
  encryptedData:
    nextauth-secret: AgBGpzepZwtkeN4AIDMTkyAMv5krgntF7u4XWQ6vlreUr6H9Q0grE/gldpleWjCWLbtTl8+KUeYuYAFC2rL83PiVImBXELpRRl39uZcZvIrwIFbPi2dpviYN2a+SxxFt0JvZHJ8XQumy8+DFaQp0zXPwCnDAv/LIbVMcnAA5eGtqHAQg1cGWds8ZBPEnoVOnylyhHiTG79T82ZrDuakUHo/WxnQY4g3bqVTD+ERsOEoE99VfsDWUbL7U3lNT57EWL6yXKV7I/X3kYpD1uZBLkmyt3JgBtNR5Y26MPJ91UZneQQuHs8+e2FecrPvDANS1f0W9SmNhXFHCmmzmVt2N3CAP02obVQxTD07Zr1yESElrmlNvEyykdWrTM4WU9szfvPk5v3xmM75jlD8zfXAyBuNaFE2fLKxx3+yTxH7+Y7qwyWn/e8p9ydhEgAuNfxmKYmIGcLcltEFkUJHMhf1qeDcD6kE0pJ8crHNEtR0lcOqz2bb+JY/AvGQzq1vBtJe3p5DwCSZCODtErJPVb2P0Ub6alzumHTDKbKlxf/RUoCxtsGtJeAQGvYagukZOt89yUA7LBNTt1D7bvHhAjUZ8/7wcXxFaLPYAh+Rj++wJAhHtIG34pODGIDQ3HjkcfTIs749ySuRyv+WoAbG+e6d/mVF/qYjz2Cmh5qP1lVM1uX88eFVKuJ3LfIY8bMBauaEq3E4xc1//5h2KnttkFbLoFMGJl5SsqDu/E4pLPAP4iU2fGMjKrf2J5dicmJSAnXcxPmY=
    openai-api-key: AgAEsa4QddnnkNLZ39iCD22h5k9LdeZ7U6U3PkOfCoGzjxOHUyP4rCrYadP88t4L8M3BBRzrY+NdTCQRvLVh9pQ2rfcip8KYkpfJbJ8BmL31cJNzKVoksHeYX5+XwVkaHvg+v8gw+tqv2uZukDQfSZuZBs7SgPoAMkAUWzU5s+0rTHP29NEvKyLbf3Hw007Mu0satmd4DQxElzQ5sMxmRcFN5Kj2mVy1I/V9xxOi7fkKDqNzQMTL8aChRLOZ/7ltg8veBu+cZVzDFl4hHWAKBhQmd/ptBikOuBYDDpzTmJvP1/t0mewy0eA1V/LpRHYpHd7AQP+wjpJqEAzLuL5IDdtXw2E12Q53FQNmC4EN2nZ54yRnz0NpRiBuFq1x9CG7JB7ZufWUSXj486SNtMkh86G3stnVpLuCgS+77xy5d7KwLZdz7TABKwCqBa4Q2+GMlyo93+kAIjpciVdxJ58Lv4oFe8Fjrpl4cxiHvvgz9YveLISlKSlLvApi4bwrqeEAWniEpzyg+KNosaTgNWeq/ei//308Kain94Q/6RsFOL+izIiGudvuVkKrRMfwgo3gKKlTTanvA1XW1kKzD2CmmeCMWeDEXAnbEir5iNWZybdzS7H2e9WWcralIsKD+0OLlFJ1PiNDRNrFNo0FrDUSCHpgOcnQxZDBUuaH9fYkfj00p9FwO+jJfaaq6utldLwyf/jSffgD76qiaG5XFJ10hAmSq4M68HUIZBr2mwzuR75hBMxYv2og1iS89U3fXzQv+e+trltzR9jDXmUmEpMSLCiinDp1jMA671OkqRM3udQ4FgoAAJ8VdbJ8iNh8/osD0bIsR5Vf54hAWVFtLZFVZdu8R+FscERH++0OIIbO276Xs45p+bsEXRyvKq9Cbg6+L5+vWtmMkhFaxybF4UkkxfWGneV/lA==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: karakeep-secrets
      namespace: karakeep
    type: Opaque