---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secrets
  namespace: karakeep
spec:
  encryptedData:
    nextauth-secret: AgCG/3mx4+exKqRnes++IzZDMnIV3Wvfyi1Vwlvjl0z0+r77a9rx+Ns3NxEdlS/VX2N3nTO0f3gDjoBXz4Gkbrlo/fLBfIsMcuowjzdexmGt/lhvpmGX38x7QU2RTR6mDzMhY+d/gxGSY0r94h85AsG52fFuo3LS9xN1h0QTXSVZ3pD2LgoV/WVIfeATeeGZvZu+ijK36qJObkrKmhFoFTTwRKIeUZT62AuJ/aIGYU/SThUKJuJzfZoCeZsHXp/gHri+I79y2G0POZH9StZVCkKcrw4tl7DyLAfxTFWFJZKWuLndb+o/7Gtj4wrVJInsDe1l/N/09d4ap7EMKE150qhYcfY3mYMLwZk0hhjsI+U6s3BkLQN/U8dhcJV753aVeNZGNUxuExn2XCR/p5p1hgtfQCiUB8ui90tNworLadADFsRiFMqVKY0eYox7eenX2T9QAa1VmtqJ8l4HtNI/MR8ilLQg7gw6EKCOBW5D3DERkBKgedwoA/jziYE9PmbBx93az6gJzT2/+OWqk8ckatBW10GprPQAVzE93paaxB3hTEWv4ASr44N1QhVc/fPhs7UVuFjWA35hbylCJia7ed/nxPuGDB4rBgrlJoNwTyUWTn/c5jrFmdJVel4RS0EnF0W/d/YjNwYXFdbglfSYdyycpa2leu04DO1YbzcgBJyFDIrE2AgjcVTvD4gBSWXJsS/Uh0u311f6arTjBKAHwcQmzH5MBwCbQY8roEgdRcaKVTpTc1z712UDmTZGHsmFYLE=
    openai-api-key: AgCkTXG/3WxV8E7Q9ENpD/atixF1V/T/+p0A0OovhbZNhkMSFOSatcozF+iXu7kHYatWbfJzWtvZxRzX3mBgfawjuitNHusQuqc8jGtfhfvDHjDm1f5byzm8ubpUw2zC49kqF5uAKY0qSOBSLRU4LhO1u49QQKUOE623RsXOiCLBUaF/5RE3ace5cpEjL/eSxtfySapBM3CrxDu/aSs82GPzyK525vRzvDHEMGOWeT2KTKDmvoueQCBcjyf27VbaXMEk4RodPSYJoPkT3JOmyyBEt+TLOOgrQ9RTtdFn63yJAphjbLprW4Q/nycrZnp5BNdI7PA/IUIBox6PpRwmvQlgK+OBOMdx65fCC+Ge7ofh8fzXVD+E2iIvVJMJqV5RIF1D5AYT26jBm4Pu2Ny6Vb4qk2SeODw+VrtLpzkKHm/gbScOeeQgNarnbo9w4nbtRsAn5+NPK0p/+q6Usri0sfbn1bBtd64F8TfWUFdtLp/jD2TWb/KqhzqyJVsrhhhGUaStuOlzmqXNCL93iOu6txSLnBYkTIJOSHlI0YqOx4uEWzy959E+QOXkr62f5vtCDGxp0SudMgV1HaGxjlaTbJxNls3ZuuYgdRb+Qv/Ebndc49mmE2wGXJw8EvMrd1bPxF7JzrsvuzIEtIi4lmflEfix5lhOiB6CjRUgSAXHzQNPIqI3I99H8g7Da5Wy7rIcX0uZQlt5QXyEWuvudwwnCeMeid4RLOv5aUD7GG/+sP77HiJhUFYMHtksxZgxBw2JLSfF16UcCfNK9ZogjhkveRoxNQThJi7hXKmvZJmXXzpm8xoarJCkZNYB9+kfwiC8QaS8yIxjJl8bzt45NnP79dNee6rIfo6+wuwNr1a8v+FmjF2wXqfe5PxKwr4tLyYyadeO7Rmo87Jy8swccsQ6IV96I8XU+A==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: karakeep-secrets
      namespace: karakeep
    type: kubernetes.io/basic-auth
