---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-db-credentials
  namespace: semaphore
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: semaphore-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-semaphore-password
    - secretKey: username
      remoteRef:
        key: postgres-semaphore-username
    - secretKey: client-secret
      remoteRef:
        key: semaphore_client_secret
    - secretKey: client-id
      remoteRef:
        key: semaphore_client_id
