---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore-secrets
  namespace: semaphore
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: semaphore-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
        SEMAPHORE_OIDC_PROVIDERS: |
          {
            "authentik": {
              "display_name": "Sign in with authentik",
              "provider_url": "https://auth.torsteinbo.net/application/o/semaphore/",
              "client_id": "{{ .client_id }}",
              "client_secret": "{{ .client_secret }}",
              "redirect_url": "https://semaphore.torsteinbo.net/api/auth/oidc/authentik/redirect",
              "username_claim": "username",
              "name_claim": "name",
              "email_claim": "email",
              "scopes": ["openid", "email", "groups"]
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: postgres-semaphore-password
    - secretKey: username
      remoteRef:
        key: postgres-semaphore-username
    - secretKey: client_secret
      remoteRef:
        key: semaphore-auth-client-secret
    - secretKey: client_id
      remoteRef:
        key: semaphore-auth-client-id
