apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Immich photo management application

resources:
  - ../../../apps/immich/application.yaml

labels:
  - pairs:
      app-category: media
      app: immich
      requires: postgres
