apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-authentik-secret
  namespace: argocd
spec:
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
      data:
        # Dex OIDC connector client secret (base64 encoded by ExternalSecrets)
        dex.authentik.clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd-auth-client-secret
