apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-authentik-secret.yaml
  - argocd-cm-patch.yaml
  - argocd-rbac-cm-patch.yaml

# Use server-side apply to merge with existing ConfigMaps
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
