apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Harbor container registry - optional infrastructure

resources:
  - ../../../infrastructure/harbor.yaml

labels:
  - pairs:
      component: infrastructure
      tier: registry
      feature: harbor
