---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-auth-secrets
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: openwebui-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: openwebui-auth-client-id
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: openwebui-auth-client-secret
