apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Buildarr - Configuration automation for *ARR applications

resources:
  - ../../../apps/buildarr/application.yaml

labels:
  - pairs:
      app: buildarr
      app-category: utility
      app-stack: media
