apiVersion: apps/v1
kind: Deployment
metadata:
  name: bambustudio
  namespace: bambustudio
  labels:
    app: bambustudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bambustudio
  template:
    metadata:
      labels:
        app: bambustudio
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bambustudio
          image: lscr.io/linuxserver/bambustudio:latest
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          env:
            - name: DARK_MODE
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: bambustudio-data
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: bambustudio-data
          persistentVolumeClaim:
            claimName: bambustudio-data
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
