apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bambustudio
  namespace: bambustudio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: bambustudio.torsteinbo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bambustudio
                port:
                  number: 3000
