apiVersion: v1
kind: Service
metadata:
  name: bambustudio
  namespace: bambustudio
spec:
  selector:
    app: bambustudio
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
