apiVersion: v1
kind: Service
metadata:
  name: bambustudio
  namespace: bambustudio
spec:
  selector:
    app: bambustudio
  ports:  
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
