apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    azurekv:
      tenantId: 80bd2496-6210-4cee-8517-d3036473cffe
      vaultUrl: https://kv-homelab-cmn.vault.azure.net/
      auth:
        servicePrincipal:
          clientId:
            name: azure-secret-sp
            namespace: external-secrets
            key: ClientID
          clientSecret:
            name: azure-secret-sp
            namespace: external-secrets
            key: ClientSecret
