apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: AzureKeyVault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-homelab-cmn.vault.azure.net/
      tenantId: 80bd2496-6210-4cee-8517-d3036473cffe
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-secret-sp
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          namespace: external-secrets
          key: ClientSecret
