apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base kustomization for all GitOps applications
# This serves as the foundation that overlays can build upon

resources:
  - ../bootstrap/argocd-config.yaml
  - ../bootstrap/projects.yaml

# Common labels applied to all resources
commonLabels:
  managed-by: argocd
  gitops-repo: gitops
