apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  namespace: traefik
  annotations:
    # Optional: Add Traefik-specific annotations here
     traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  # ingressClassName not needed - Traefik is default
  rules:
  - host: traefik.torsteinbo.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik traefik
            port:
              number: 9000