---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-config
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: sabnzbd-config
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: sabnzbd-api-key
    - secretKey: username
      remoteRef:
        key: sabnzbd-username
    - secretKey: password
      remoteRef:
        key: sabnzbd-password
    - secretKey: usenet_server_host
      remoteRef:
        key: usenet-server-host
    - secretKey: usenet_server_port
      remoteRef:
        key: usenet-server-port
    - secretKey: usenet_server_username
      remoteRef:
        key: usenet-server-username
    - secretKey: usenet_server_password
      remoteRef:
        key: usenet-server-password
