apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  type: NodePort
  selector:
    app: immich-server
  ports:
    - protocol: TCP
      port: 2283
      targetPort: 2283
      nodePort: 30283
      name: http
