---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://semaphoreui.github.io/charts
      chart: semaphore
      targetRevision: v2.17.0
      helm:
        releaseName: semaphore
        values: |
          database:
            type: postgres
            host: postgresql-rw.postgres.svc
            port: 5432
            name: semaphore
            usernameFromSecret: true
            usernameKey: username
            passwordKey: password
            existingSecret: semaphore-db-credentials
          admin:
            create: true
            username: admin
    - repoURL: git@github.com:storsteinbono/gitops.git
      targetRevision: HEAD
      path: apps/semaphore/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
