---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-config
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: authentik-config
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik-secret-key
    - secretKey: db_user
      remoteRef:
        key: postgres-authentik-username
    - secretKey: db_password
      remoteRef:
        key: postgres-authentik-password
    - secretKey: bootstrap_password
      remoteRef:
        key: authentik-bootstrap-password
    - secretKey: bootstrap_token
      remoteRef:
        key: authentik-bootstrap-token
