---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-secrets
  namespace: netbird
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: netbird-secrets
    creationPolicy: Owner
  data:
    - secretKey: NETBIRD_TURN_SECRET
      remoteRef:
        key: netbird-turn-secret
    - secretKey: NETBIRD_DATASTORE_ENC_KEY
      remoteRef:
        key: netbird-datastore-enc-key
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-netbird-password
