---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-secrets
  namespace: netbird
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: netbird-secrets
    creationPolicy: Owner
  data:
    - secretKey: NETBIRD_AUTH_CLIENT_ID
      remoteRef:
        key: netbird-auth-client-id
    - secretKey: NETBIRD_TURN_SECRET
      remoteRef:
        key: netbird-turn-secret
    - secretKey: NETBIRD_MANAGEMENT_SECRET
      remoteRef:
        key: netbird-management-secret
    - secretKey: NB_FIELD_ENCRYPTION_KEY
      remoteRef:
        key: netbird-datastore-enc-key
        decodingStrategy: None
    - secretKey: NETBIRD_AUTH_CLIENT_SECRET
      remoteRef:
        key: netbird-auth-client-secret
