apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird-ingress
  namespace: netbird
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: netbird.torsteinbo.net
      http:
        paths:
          # API (Management)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: netbird-management
                port:
                  number: 80
          # gRPC (Management)
          - path: /management.
            pathType: Prefix
            backend:
              service:
                name: netbird-management
                port:
                  number: 33073
          # gRPC (Signal)
          - path: /signalexchange.
            pathType: Prefix
            backend:
              service:
                name: netbird-signal
                port:
                  number: 10000
          # OAuth (Management)
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: netbird-management
                port:
                  number: 80
          # Dashboard (Fallback / Root)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird-dashboard
                port:
                  number: 80
  tls:
    - hosts:
        - netbird.torsteinbo.net
