---
apiVersion: v1
kind: Namespace
metadata:
  name: netbird
  labels:
    name: netbird
    app.kubernetes.io/name: netbird
    app.kubernetes.io/component: vpn
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
